[workspace]
resolver = "3"
members = [
  "crates/nx-core",
  "crates/nx-api",
  "crates/nx-cli",
  "crates/nx-store",
  "crates/nx-sync",
  "crates/nx-net",
  "crates/nx-sdk",
]

exclude = [
  "examples/*",
  "fuzz",
]

[workspace.package]
license = "Apache-2.0"

[profile.profiling]
inherits = "release"
debug = true
strip = false
