use crate::__alloc::vec;
use crate::__alloc::vec::Vec;

use crate::error::{NxError, Result};
use crate::ffi;

const ERR_BUF_TOO_SMALL: i32 = -2;
const ERR_INTERNAL: i32 = -3;
const HASH_LEN: usize = 32;
const MAX_RANDOM_BYTES: usize = 1024 * 1024;

fn map_hash_rc(rc: i32, out: [u8; HASH_LEN]) -> Result<[u8; HASH_LEN]> {
    match rc {
        32 => Ok(out),
        ERR_BUF_TOO_SMALL => Err(NxError::BufferTooSmall),
        ERR_INTERNAL => Err(NxError::Internal),
        c if c < 0 => Err(NxError::UnknownCode(c)),
        _ => Err(NxError::UnknownCode(rc)),
    }
}

fn validate_random_len(len: usize) -> Result<()> {
    if len > MAX_RANDOM_BYTES {
        return Err(NxError::BufferTooSmall);
    }
    Ok(())
}

/// cryptographically secure random bytes generated by the host.
pub fn random_bytes(len: usize) -> Result<Vec<u8>> {
    validate_random_len(len)?;
    let len_u32 = u32::try_from(len).map_err(|_| NxError::Internal)?;
    let mut out = vec![0u8; len];
    let rc = unsafe { ffi::random_bytes(out.as_mut_ptr() as u32, len_u32) };

    match rc {
        n if n == len_u32 as i32 => Ok(out),
        ERR_INTERNAL => Err(NxError::Internal),
        c if c < 0 => Err(NxError::UnknownCode(c)),
        _ => Err(NxError::UnknownCode(rc)),
    }
}

/// SHA-256 digest of `input`.
pub fn hash_sha256(input: &[u8]) -> Result<[u8; HASH_LEN]> {
    let mut out = [0u8; HASH_LEN];
    let input_len = u32::try_from(input.len()).map_err(|_| NxError::Internal)?;
    let rc = unsafe {
        ffi::hash_sha256(
            input.as_ptr() as u32,
            input_len,
            out.as_mut_ptr() as u32,
            out.len() as u32,
        )
    };

    map_hash_rc(rc, out)
}

/// BLAKE3 digest of `input`.
pub fn hash_blake3(input: &[u8]) -> Result<[u8; HASH_LEN]> {
    let mut out = [0u8; HASH_LEN];
    let input_len = u32::try_from(input.len()).map_err(|_| NxError::Internal)?;
    let rc = unsafe {
        ffi::hash_blake3(
            input.as_ptr() as u32,
            input_len,
            out.as_mut_ptr() as u32,
            out.len() as u32,
        )
    };

    map_hash_rc(rc, out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn random_bytes_rejects_oversized_request_before_allocating() {
        assert_eq!(
            validate_random_len(MAX_RANDOM_BYTES + 1),
            Err(NxError::BufferTooSmall)
        );
    }
}
